### ISSUE TITLE
/usr/bin/env: ‘node\r’: No such file or directory

### ISSUE THREAD

**Issue by myfreax** [vilien/justreq-cli#1]
I found error. When i try run `justreq init` 

```shell
/usr/bin/env: ‘node\r’: No such file or directory
```

If you coding on the Mac,You can look this  [Line breaks](https://github.com/nwjs/nw-builder/issues/75)

addition:
```shell
➜  justreq-cli git:(master) ✗ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial
```

**Comment by vilien** [comment]
Thx, I've removed '\r' in files

**Comment by myfreax** [comment]
It work well，very good ! :tada:
